# Generated by Django 5.2.4 on 2025-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_address_options_remove_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(blank=True, default='N/A', max_length=255, verbose_name='Address Line 1'),
        ),
    ]
