# Generated by Django 5.2.4 on 2025-11-03 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_address_address_line1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for this user', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successful referrals'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
