# Generated by Django 5.2.4 on 2025-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
    ]
