# Generated by Django 5.2.4 on 2026-01-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0015_alter_customuser_options_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique referral code for this user', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit_refund_cancel', 'Order Cancellation Refund'), ('credit_refund_return', 'Order Return Refund'), ('credit_referral', 'Referral Reward'), ('credit_admin', 'Admin Credit'), ('debit_purchase', 'Order Purchase'), ('debit_admin', 'Admin Debit')], help_text='Type of transaction', max_length=30),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referral_code'], name='users_custo_referra_4cecc0_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
    ]
