# Generated by Django 5.2.4 on 2025-08-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_c80f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_is_emai_462fb1_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
