# Generated by Django 5.2.4 on 2025-11-03 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_referral_code_customuser_referral_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit_refund_cancel', 'Order Cancellation Refund'), ('credit_refund_return', 'Order Return Refund'), ('credit_admin', 'Admin Credit'), ('debit_purchase', 'Order Purchase'), ('debit_admin', 'Admin Debit')], help_text='Type of transaction', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive for credit, negative for debit)', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=10)),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='Order ID or other reference', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_walle_created_8cdd16_idx'), models.Index(fields=['wallet', '-created_at'], name='users_walle_wallet__7a1893_idx')],
            },
        ),
    ]
