# Generated by Django 5.2.4 on 2026-01-16 09:30

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_address_address_line1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Alphabetic characters only.', max_length=150, validators=[users.validators.AlphabeticValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Alphabetic characters only.', max_length=150, validators=[users.validators.AlphabeticValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digit Indian mobile number (e.g., 9876543210)', max_length=10, null=True, validators=[users.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB)', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3-30 characters. Letters, numbers, and underscore only.', max_length=150, unique=True, validators=[users.validators.UsernameValidator()]),
        ),
    ]
