# Generated by Django 5.2.4 on 2025-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_options_productimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='zoom_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/zoom/'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='zoom_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/zoom/'),
        ),
    ]
