# Generated by Django 5.2.4 on 2025-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_orderreturn_admin_notes_orderreturn_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
