# Generated by Django 5.2.4 on 2025-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay (Online)'), ('wallet', 'Wallet Payment')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Awaiting Return'), ('rejected', 'Rejected'), ('completed', 'Completed - Refunded')], default='pending', max_length=20),
        ),
    ]
